### PR TITLE
Include exercise name in submission feedback

### LINKED ISSUE #71: [FEATURE] Add name of exercise to submission results
To avoid confusion it would be nice if the name of the exercise was mentioned in the notification (just like in the PyCharm plugin).
image
image
Solution was correct > Your solution to "`exercise_name`" was correct!

image
image
Solution was incorrect > Your solution to "`exercise_name`" was incorrect: `number` tests failed.

### PR DESCRIPTION
**Pull request by thepieterdc**
Fixes #71 

Also refactors the submission handler because it was outdated

### CODE REVIEW

File: src/commands/submitSolution.ts [hunk 1]
```diff
@@ -102,20 +106,21 @@ async function handleIdentify(
...
+            `Solution to "${exercise.name}" has been accepted!`,
             ...[FEEDBACK_VIEW_RESULTS],
         );
     }
 
     // Incorrect solution.
     if (submission!.status === "wrong") {
         return window.showWarningMessage(
-            "Solution was incorrect.",
+            `Solution to "${exercise.name}" was not incorrect: ${submission.summary}`,
```
Comment (BTWS2) [inline src/commands/submitSolution.ts:123]: This should be `was not correct`. Thank you for the commits.

**Review by stijndcl — APPROVED** [review]
