### PR TITLE
Warning for different exercises with same name

### LINKED ISSUE #102: [FEATURE] Change name in command palette in case of different exercises with same name
**Briefly describe the feature idea:**
I would like to suggest a new way to handle the case of different exercises with same name.
image

It's confusing/unexpected for the user that there is a new window. Since a certain workplace is opened, we assume the file should be in the same folder, only the name should change. I would propose that the user could enter/modify the name in the command palette, just like the [File Utils Visual Studio Code extension `File Utils: Rename` command](https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils) (fileutils.renameFile). The name (and not the extension) should be selected and the user should enter the new filename and press enter (see image).

image

### PR DESCRIPTION
**Pull request by BTWS2**
image
Closes #102.

### CODE REVIEW

File: src/commands/createNewExercise.ts [hunk 1]
```diff
@@ -39,6 +39,7 @@ export async function createNewExercise(exercise: Exercise) {
 
         // File already exists, but it is a different exercise. Ask the user to
         // provide a different filename.
+        window.showWarningMessage("Choose a different filename. File already exists, but it's a different exercise.");
```
Comment (thepieterdc) [inline src/commands/createNewExercise.ts:42]:
```suggestion
        window.showWarningMessage("A file with the same name already exists on your system for a different exercise already exists. Please choose another name.");
```

Comment (BTWS2) [reply src/commands/createNewExercise.ts:42]: I chose to make it short and place the instruction first, because most users won't expand the notification. This results in losing the rest of the sentence. Do you have another suggestion?
image

Comment (stijndcl) [reply src/commands/createNewExercise.ts:42]: I'd maybe suggest something like "This filename is already in use for a different exercise..." which contains the most important info before being cut off by the notification, and is ~15 characters shorter than what is cut off in the screenshot so it should fit on the notification.

Extra details can be added in the rest of the sentence, which can be cut off without losing any information. If it's followed up by, for example, "... choose a different name for this exercise." then it should still display "choose a diff..." which I feel should be clear enough to the users.

**Review by thepieterdc — APPROVED** [review]

**Review by thepieterdc — APPROVED** [review]
